### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by sasakits** [guxinqian/Simple-CCReID#1]
Hi Thanks for the great work

I am looking for pretrained model
Do you have a plan to release it?

**Comment by guxinqian** [comment]
Hi! Training this model on six clothes-changing re-id datasets (using 2 2080Ti GPUs) can be finished within 15 hours, so we don't have the plan to release the pre-trained models.

**Comment by sasakits** [comment]
Thank you for response. 
I understand it. I will try it.
