### ISSUE TITLE
Fail to reproduce the results in the paper

### ISSUE THREAD

**Issue by MolunYu** [guxinqian/Simple-CCReID#15]
Thanks for your great work!

I want to reproduce the results in the paper, but I always got 38.3% Rank-1 on LTCC and 54.6% Rank-1 on PRCC. My GPUs are two TITAN XP and I have tried at least 5 times.

I make sure I have followed the environment requirements and commands in the [script.sh](https://github.com/guxinqian/Simple-CCReID/blob/main/script.sh). Could you please give me some suggestions?

**Comment by TaihuLight** [comment]
@guxinqian @MolunYu Could you publish the trained models?

**Comment by guxinqian** [comment]
I‘m sorry for the late reply. Different machines, environments, and random numbers may lead to different reproduction results. +- 2% is reasonable. The results in this paper are reproduced using 'nn.DataParallel' (DP), while this code uses the faster 'nn.parallel.DistributedDataParallel' (DDP). In my experimental environment, DDP will get higher performance, except for LTCC dataset. 38.3% rank-1 on LTCC is reasonable. If you want to get the results in this paper, changing DDP to DP may help you.

**Comment by guxinqian** [comment]
@TaihuLight  Sorry, I have graduated now. The pre-trained model is on the school's server, and I no longer have permission to download it. You can train yourself.

**Comment by breeze0011** [comment]
> Thanks for your great work!
> 
> I want to reproduce the results in the paper, but I always got 38.3% Rank-1 on LTCC and 54.6% Rank-1 on PRCC. My GPUs are two TITAN XP and I have tried at least 5 times.
> 
> I make sure I have followed the environment requirements and commands in the [script.sh](https://github.com/guxinqian/Simple-CCReID/blob/main/script.sh). Could you please give me some suggestions?

Hello, do you still remember this question? Can you tell me the values of your rank10 and map?
