### ISSUE TITLE
I als fail to reproduce the results

### ISSUE THREAD

**Issue by ykding666** [guxinqian/Simple-CCReID#16]
I have two 3090,and my result in prcc,the rank1 is 53.4

**Comment by guxinqian** [comment]
Different machines, environments, and random numbers may lead to different reproduction results. +- 2% is reasonable. The results in this paper are reproduced using 'nn.DataParallel' (DP), while this code uses the faster 'nn.parallel.DistributedDataParallel' (DDP). You can try to change DDP to DP.

**Comment by ykding666** [comment]
Thank your，reply，I want to ask other question.
1. The code in github ,the parameters do not need to be changed?And only run the script.sh.

**Comment by ykding666** [comment]
2.Can you tell me which gpu you use

**Comment by guxinqian** [comment]
1. only run the script.sh
2. two 2080Ti

**Comment by BRIAN-THOMAS-02** [comment]
Hi @guxinqian I am unable to run the code, please guide me in the same

Could you please drop any platform so that we could communicate and solve this problem
