### ISSUE TITLE
I als fail to reproduce the results

### ISSUE THREAD

**Issue by yingyingc** [guxinqian/Simple-CCReID#18]
Hello, in the case of consistent parameter settings, the results I reproduced in the CCVID dataset: general mAP=77.9%, CC mAP=75.7%, and the results in your paper cannot be reproduced. Can I compare the experimental results in my paper with the results I have reproduced?

**Comment by guxinqian** [comment]
Since the scale of CCVID is not very large, the results in this dataset are not stable. You can test multiple times and take the average result in your paper.
