### ISSUE TITLE
One question about ablation studies.

### ISSUE THREAD

**Issue by breeze0011** [guxinqian/Simple-CCReID#20]
Your work was so interesting and it was attractive to me.
If I want to achieve this, how should I set the .yaml.
![image](https://github.com/guxinqian/Simple-CCReID/assets/130063990/bdb3f6fb-730c-4d8a-8e8a-fc3b6f859324)

**Comment by breeze0011** [comment]
And if use PCB, can CC top1 reach this?
![image](https://github.com/guxinqian/Simple-CCReID/assets/130063990/7e717463-75fb-4fef-9a0c-2c5e3578fc80)

**Comment by guxinqian** [comment]
1. Remove the clothes classifier, clothes classification loss, and CAL, then add triplet loss.
2. This result is from another paper.
