### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by BoomShakaY** [guxinqian/Simple-CCReID#9]
Hi, when I reproduce the visualizaiton (heatmap) as Fig.1 and Fig.5 in the paper, the feature heatmap of the model after training looks more like the middle one, which focuses on upper body and feet.

I use the image feature of the ResNet50 after line 33 `x = self.base(x) ` in  ` img_resnet.py `

I would be grateful if you could give me some help with this. Or can you release the visualization code?  It would be much appreciated. 

Here is an example of my visulization, which is origin image, the heatmap and their overlap. 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/26376754/183571476-a89992de-e846-47a0-8c66-d82110e3f253.png">

**Comment by guxinqian** [comment]
1. Visualizing the features after stage-2 or stage-3 of ResNet-50 may be more salient. 
2. The visualization results in our paper were produced by a earlier version of our code, where only global avg pooling is used after ResNet. To improve the accuracy, we change global avg pooling as global avg&max pooling, but we do not evaluate its influence on visualization results.
